# Generated by Django 4.1.3 on 2022-11-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.TextField()),
                ('artist', models.CharField(max_length=20)),
                ('album', models.CharField(max_length=50)),
                ('track_id', models.CharField(max_length=50)),
            ],
        ),
    ]
